### ISSUE TITLE
Tflite model support 

### ISSUE THREAD

**Issue by samsgates** [lshug/first-order-model-tf#21]
- Is this tflite model support android app? if yes, do you have any sample code to test run?

**Comment by lshug** [comment]
Hello. The TF Lite model can be run inside Android. I can't provide sample code, but here's how you can do it:

 * Load the three models (kp_detector, generator, process_kp_driving) as org.tensorflow.lite.Interpreter objects kpDetector, generator, and processKpDriving
 * Load your source image bitmap into a nByteBuffer (load as floats first, then normalize by dividing by 255.0, then load into the ByteBuffer)
 * Prepare input and output hashmaps for the kp detector. For the input hashmap, jump map the rewound source image ByteBuffer to key "img".  For outputs, use output names as keys, and ByteBuffers with correct allocations as values. Each floating point is four bytes, so e.g. for an output tensor with shape ```batch_size * 10 * 2 * 2``` (kpDetector's output "jacobian"), use ```ByteBuffer.allocate(batchSize * 10 * 2 * 2 * 4)```. Inspect TF Lite files to find the output shapes.
 * Run the kpDetecctor with interpreter's runSignature method, using the input and output hashmaps as arguments. Be sure to rewind the output ByteBuffers afterwards.
 * For each frame batch:
    1. Load the frame bitmaps into a ByteBuffer
    2. Prepare the hashmaps for kpDetector, and run its runSignature on the driving video frames
    3. Prepare processKpDriving's input and output hashmaps. For scalar-value inputs (```use_relative_jacobian``` and ```adapt_movement_scale```), load float values of 0 or 1 into four-byte ByteBuffers. Run processKpDriving.runSignature on the prepared hashmaps.
    4. Finally, prepare the hashmaps for the generator, using the correct output ByteBuffers from the previous steps as inputs (source image, source image's kps and jacobians, normalized driving video frame batch kps and jacobians, and possibly ```source_image_scaled``` if prescale was enabled during build), and a hashmap with a single key "prediction" mapped to a ```batch * h * w * 3 * 4```-sized ByteBuffer. Run the generator's runSignature.
    5. Extract the bitmaps from the prediction ByteBuffer.
