### ISSUE TITLE
Need higher resolution

### ISSUE THREAD

**Issue by TRONBFFL** [lshug/first-order-model-tf#23]
What do I need to do to generate a larger and different size resolution?
from 256x256

To 768x576?

**Comment by lshug** [comment]
Hello. Sorry for the late reply. I don't actively develop this project anymore.

What you would need is checkpoints of the KP detector and the generator trained on images with said resolutions, along with the accompanying YAML configs. I do not have such checkpoints, and I don't know if they're available openly.
