### ISSUE TITLE
I can't find testlite.py

### ISSUE THREAD

**Issue by Apokar** [lshug/first-order-model-tf#24]
@lshug Hi, has the name of this file been changed? Can I still use it to check if the tflite model works correctly?

**Comment by lshug** [comment]
Hello. As I remember I replaced testlite.py with TFLite signature runner-based functionality in run.py as soon as TFLite signature runner became available in Tensorflow. TFLite models can be tested after build by running `run.py` with a not-so-awesomely-named `--target tflite` argument. When this argument is provided, `run.py` uses `load_models_tflite` from `utils.py` to load the models, which returns callables with the same signature as SavedModels and which are then used in `animate.py` the same way.
