### ISSUE TITLE
need help about android app development

### ISSUE THREAD

**Issue by Apokar** [lshug/first-order-model-tf#25]
First of all, I would like to thank you for your help in converting the tflite model. Now, I would like to continue developing a demo level app to use the tflite model for inference and generating videos

However, due to my lack of experience in Android development, I have simplify your Python inference code to around 200 lines, and then use ChatGPT to convert it into Java code. However, the app does not run properly, and the problems is about buffer? like this: "Cannot copy to a TensorFlowLite tensor (serving_default_kp_source_jacobian: 0) with 160 bytes from a Java Buffer with 786432 bytes."

Sorry to bother you, I was wondering if you could provide some experience or advice. Thank you for taking the time to read my issues.

**Comment by lshug** [comment]
Hello. Quoting my reply to a similar question from a couple of years ago about running the model within android apps:

 * Load the three models (kp_detector, generator, process_kp_driving) as org.tensorflow.lite.Interpreter objects kpDetector, generator, and processKpDriving
 * Load your source image bitmap into a nByteBuffer (load as floats first, then normalize by dividing by 255.0, then load into the ByteBuffer)
 * Prepare input and output hashmaps for the kp detector. For the input hashmap, jump map the rewound source image ByteBuffer to key "img".  For outputs, use output names as keys, and ByteBuffers with correct allocations as values. Each floating point is four bytes, so e.g. for an output tensor with shape ```batch_size * 10 * 2 * 2``` (kpDetector's output "jacobian"), use ```ByteBuffer.allocate(batchSize * 10 * 2 * 2 * 4)```. Inspect TF Lite files to find the output shapes.
 * Run the kpDetecctor with interpreter's runSignature method, using the input and output hashmaps as arguments. Be sure to rewind the output ByteBuffers afterwards.
 * For each frame batch:
    1. Load the frame bitmaps into a ByteBuffer
    2. Prepare the hashmaps for kpDetector, and run its runSignature on the driving video frames
    3. Prepare processKpDriving's input and output hashmaps. For scalar-value inputs (```use_relative_jacobian``` and ```adapt_movement_scale```), load float values of 0 or 1 into four-byte ByteBuffers. Run processKpDriving.runSignature on the prepared hashmaps.
    4. Finally, prepare the hashmaps for the generator, using the correct output ByteBuffers from the previous steps as inputs (source image, source image's kps and jacobians, normalized driving video frame batch kps and jacobians, and possibly ```source_image_scaled``` if prescale was enabled during build), and a hashmap with a single key "prediction" mapped to a ```batch * h * w * 3 * 4```-sized ByteBuffer. Run the generator's runSignature.
    5. Extract the bitmaps from the prediction ByteBuffer. 
 
 This was years ago, and some APIs might have changed, but the general procedure should be the same.

**Comment by Apokar** [comment]
I really appreciate your selfless help！

**Comment by Apokar** [comment]
Hello author, based on the information  you provided me above and python code, I have drawn a flowchart to streamline the process of models inference. Could you please help me check if there are any issues with my understanding? Thank you for your help!
![2](https://github.com/lshug/first-order-model-tf/assets/25199579/e93297c1-008e-448f-8c92-5e6cb803541f)
![tf1](https://github.com/lshug/first-order-model-tf/assets/25199579/bb935345-41b6-4257-9a13-21db4718dea7)
