### ISSUE TITLE
Divergence from the original pytorch version's ouput 

### ISSUE THREAD

**Issue by lshug** [lshug/first-order-model-tf#5]
I'll go ahead with investigating this.

![source_2](https://user-images.githubusercontent.com/6432677/113621786-befbc880-9664-11eb-85c4-31b1ef15ba83.png)

https://user-images.githubusercontent.com/6432677/113621789-c15e2280-9664-11eb-9080-cb99b72d7bd6.mp4

https://user-images.githubusercontent.com/6432677/113621792-c1f6b900-9664-11eb-8192-8d1e590f104c.mp4

Original FOM result:

https://user-images.githubusercontent.com/6432677/113622451-b35cd180-9665-11eb-9b01-df36cae74dac.mp4

_Originally posted by @HashedViking in https://github.com/lshug/first-order-model-tf/issues/4#issuecomment-813624055_

**Comment by lshug** [comment]
@HashedViking So far I haven't been able to reproduce this. Can you confirm that the difference isn't caused by running one of the versions with relative or adapt_movement_scale options and the other without?

**Comment by lshug** [comment]
@HashedViking I'm confirming that the difference was caused by running with --relative (default for vox) in the original and without --relative in tf version. This is the output I get when running with testlite.py with --relative (truncated to first 32 frames). It is identical to the result you got with the original.

https://user-images.githubusercontent.com/73127106/113631568-b1e9d400-967a-11eb-9046-99fd7266350e.mp4

**Comment by HashedViking** [comment]
@lshug Right, I can confirm that too
